name: Gerar APK Hydra Agro

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar dependências
        run: npm ci

      - name: Gerar projeto Android
        run: |
          npm run build
          npx cap sync android

      - name: Gerar APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: hydra-agro-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk